version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/wordpress/nginx-proxy/docker-compose.d/certs:/etc/nginx/certs:ro
      - /home/wordpress/nginx-proxy/docker-compose.d/htpasswd:/etc/nginx/htpasswd
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/wordpress/nginx-proxy/nginx.conf:/etc/nginx/conf.d/my_proxy.conf
    restart: always
    networks:
      - common_link

  letsencrypt-nginx:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx
    privileged: true
    volumes:
      - /home/wordpress/nginx-proxy/docker-compose.d/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    restart: always
    networks:
      - common_link
networks:
  common_link:
    external: true