version: '2'

services:
  kusanagi-data:
    container_name: kusanagi-1
    image: busybox
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /etc/nginx/conf.d
      - /etc/httpd/conf.d
      - /etc/kusanagi.d
      - ./data:/home/kusanagi
      - /home/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    command: /bin/sh

  kusanagi-nginx:
    image: primestrategy/kusanagi-nginx:1.10.0-1
    environment:
      VIRTUAL_HOST: blog.wataridori.co.jp
      VIRTUAL_PORT: 443
      VIRTUAL_PROTO: https
      LETSENCRYPT_HOST: blog.wataridori.co.jp
      LETSENCRYPT_EMAIL: toriumi0118@gmail.com
      LETSENCRYPT_TEST: "false"
      PROFILE: blog.wataridori.co.jp
      FQDN: blog.wataridori.co.jp
      WPLANG: ja
      BCACHE: "off"
      FCACHE: "off"
    volumes_from:
      - kusanagi-data
    links:
      - kusanagi-php7:php
    external_links:
      - mariadb:mysql
    ports:
      - "443"
    restart: always
    networks:
      - common_link

  kusanagi-php7:
    image: kusanagi-php7
    external_links:
      - mariadb:mysql
    volumes_from:
      - kusanagi-data
    restart: always
    networks:
      - common_link

networks:
  common_link:
    external: true

